webapp/lottery/urls.py
# lottery/urls.py

from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'lottery'
urlpatterns = [
    path('enter/', views.enter_lottery, name='enter_lottery'),
    path('results/', views.view_lottery_results, name='view_lottery_results'),
    # Add more URLs as needed
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/webapp/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from lottery.views import signup_view, custom_logout, homepage_view
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lottery/', include('lottery.urls')),
    path('', homepage_view, name='home'),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', custom_logout, name='logout'),
    path('register/', signup_view, name='register'),
    path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
  <div class="container-fluid">
    <a class="navbar-brand fw-bold" href="{% url 'lottery:enter_lottery' %}">LottoMillions</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == urls.enter_lottery %}active{% endif %}" aria-current="page" href="{% url 'lottery:enter_lottery' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == urls.view_lottery_results %}active{% endif %}" href="{% url 'lottery:view_lottery_results' %}">Draw</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
        <div class="d-flex align-items-center">
          <span class="navbar-text fst-italic fs-6 me-2">Welcome, {{ user.username|title }}!</span>
          <a class="btn btn-outline-danger" href="{% url 'logout' %}">Logout</a>
        </div>
      {% endif %}
    </div>
  </div>
</nav>

<!-- Add this script at the bottom of the body if not already included -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

webapp/templates/signup.html
{% block content %}
  {% load static %} {% load widget_tweaks %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
  <style>
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
      font-family: 'Poppins', sans-serif;
    }
    p,
    a,
    span {
      font-family: 'Poppins', sans-serif;
    }
  </style>
  <body style="
    background: url('{% static 'lottery/bg.png' %}') no-repeat center center
      fixed;
    background-size: cover;
    display: flex;
    flex-direction: column;
    align-items: center;
    min-height: 100vh;
    margin: 50px 0 0; /* Adjust top margin to match navbar height */
    background-color: #ffd700; /* Background color */
    font-family: 'Poppins', sans-serif;
  ">
    <div style="
      display: flex;
      align-items: center;
      justify-content: center;
      flex-direction: column;
      background-color: #fff;
      padding: 20px;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      margin-top: 20px;
    ">
      <h2>Sign up</h2>
      <form method="post">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
          {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
          <div class="form-group mb-3">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }} {% for error in field.errors %}
              <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        {% endfor %}

        <div class="form-group px-4">
          <button type="submit" class="btn btn-primary pr-2">Sign up</button>
          <button type="button" class="btn btn-secondary">Cancel</button>
        </div>
      </form>
    </div>
  </body>
{% endblock %}